### ISSUE TITLE
特定ヴァージョンだけ

### ISSUE THREAD

**Issue by eggplants** [eggplants/chmd#3]
Release用に `-n 1`とか`-t, --tag "vX.Y"`で切り出せるように

---

```yml
name: 'CI'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Create Changelog
        run: |
          gem install chmd
          echo -e "CHMD<<'EOS'\n`chmd -n1`\nEOS" >> $GITHUB_ENV
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ env.CHMD }}
```
